version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Units
          command: |
            docker build . --target=unit-test
workflows:
  build-test-workflow:
    jobs:
      - build-and-test
